import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/ui/navbar/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={` antialiased`}>
        <main className=' bg-bg-color min-h-screen text-white  flex flex-col lg:flex-row '>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
